<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>HealthFlow.Hfcx.Sdk.Tools</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);CA1303</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HealthFlow.Hfcx.Sdk\HealthFlow.Hfcx.Sdk.csproj" />
  </ItemGroup>

</Project>
