package eg.gov.healthflow.hfcx.sdk.client.crossfixtures;

import com.fasterxml.jackson.databind.ObjectMapper;
import eg.gov.healthflow.hfcx.sdk.core.crypto.JweEncryption;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyFactory;
import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.Base64;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Cross-SDK JWE round-trip — Sprint P2 acceptance criterion 3.
 *
 * <p>Loads the shared fixture key pair under
 * {@code sdk-python/tests/fixtures/cross-sdk/} and decrypts the
 * Python-produced JWE compact serialization. Together with the
 * symmetric Python-side test
 * ({@code test_cross_sdk_round_trip.py}), this proves the JWE wire
 * format is byte-compatible across the two SDKs.
 *
 * <p>The Python-produced fixture is regenerated by running
 * {@code regenerate.py} in the fixture directory; the Java-produced
 * fixture is regenerated by {@link RegenerateCrossSdkJwe}.
 */
class CrossSdkRoundTripTest {

    private static final ObjectMapper JSON = new ObjectMapper();

    @Test
    void pythonProducedJweDecryptsToExpectedPlaintext() throws Exception {
        Path fixtureDir = locateFixtureDir();
        Path pythonJwe = fixtureDir.resolve("python-produced.jwe");
        Path plaintextFile = fixtureDir.resolve("plaintext.json");
        Path privateKeyPem = fixtureDir.resolve("private-key.pem");

        Assumptions.assumeTrue(Files.exists(pythonJwe),
                "python-produced.jwe missing; regenerate via "
                        + "sdk-python/tests/fixtures/cross-sdk/regenerate.py");

        RSAPrivateKey privateKey = parsePrivateKey(Files.readString(privateKeyPem, StandardCharsets.UTF_8));
        String expectedPlaintext = Files.readString(plaintextFile, StandardCharsets.UTF_8);
        String jweCompact = Files.readString(pythonJwe, StandardCharsets.UTF_8).strip();

        String decrypted = JweEncryption.decryptUtf8(jweCompact, privateKey);

        // Compare via parsed JSON to make trailing-newline / formatting
        // differences harmless.
        assertEquals(JSON.readTree(expectedPlaintext), JSON.readTree(decrypted));
    }

    @Test
    void javaProducedJweRoundTripsViaJavaItself() throws Exception {
        Path fixtureDir = locateFixtureDir();
        Path javaJwe = fixtureDir.resolve("java-produced.jwe");
        Path plaintextFile = fixtureDir.resolve("plaintext.json");
        Path privateKeyPem = fixtureDir.resolve("private-key.pem");

        Assumptions.assumeTrue(Files.exists(javaJwe),
                "java-produced.jwe missing; regenerate via RegenerateCrossSdkJwe main");

        RSAPrivateKey privateKey = parsePrivateKey(Files.readString(privateKeyPem, StandardCharsets.UTF_8));
        String expectedPlaintext = Files.readString(plaintextFile, StandardCharsets.UTF_8);
        String jweCompact = Files.readString(javaJwe, StandardCharsets.UTF_8).strip();

        String decrypted = JweEncryption.decryptUtf8(jweCompact, privateKey);
        assertEquals(JSON.readTree(expectedPlaintext), JSON.readTree(decrypted));
    }

    /** Smoke test that the SAME fixture public key encrypts → decrypts via the Java SDK. */
    @Test
    void javaRoundTripWithFixtureKeyPair() throws Exception {
        Path fixtureDir = locateFixtureDir();
        RSAPublicKey publicKey = parsePublicKey(
                Files.readString(fixtureDir.resolve("public-key.pem"), StandardCharsets.UTF_8));
        RSAPrivateKey privateKey = parsePrivateKey(
                Files.readString(fixtureDir.resolve("private-key.pem"), StandardCharsets.UTF_8));

        String plaintext = "round-trip via the fixture key pair";
        String jwe = JweEncryption.encryptUtf8(plaintext, publicKey);
        assertEquals(plaintext, JweEncryption.decryptUtf8(jwe, privateKey));
    }

    private static Path locateFixtureDir() throws IOException {
        Path candidate = Path.of("").toAbsolutePath();
        while (candidate != null) {
            Path fixtures = candidate.resolve("sdk-python/tests/fixtures/cross-sdk");
            if (Files.isDirectory(fixtures)) {
                return fixtures;
            }
            candidate = candidate.getParent();
        }
        throw new IOException("Could not locate sdk-python/tests/fixtures/cross-sdk/ from "
                + Path.of("").toAbsolutePath());
    }

    private static RSAPublicKey parsePublicKey(String pem) {
        String stripped = pem
                .replaceAll("-----BEGIN [^-]+-----", "")
                .replaceAll("-----END [^-]+-----", "")
                .replaceAll("\\s+", "");
        try {
            byte[] der = Base64.getDecoder().decode(stripped);
            KeyFactory kf = KeyFactory.getInstance("RSA");
            return (RSAPublicKey) kf.generatePublic(new X509EncodedKeySpec(der));
        } catch (Exception e) {
            throw new IllegalStateException("Failed to parse public-key.pem", e);
        }
    }

    private static RSAPrivateKey parsePrivateKey(String pem) {
        String stripped = pem
                .replaceAll("-----BEGIN [^-]+-----", "")
                .replaceAll("-----END [^-]+-----", "")
                .replaceAll("\\s+", "");
        try {
            byte[] der = Base64.getDecoder().decode(stripped);
            KeyFactory kf = KeyFactory.getInstance("RSA");
            return (RSAPrivateKey) kf.generatePrivate(new PKCS8EncodedKeySpec(der));
        } catch (Exception e) {
            throw new IllegalStateException("Failed to parse private-key.pem", e);
        }
    }
}
